quando ocorre uma excessao todo o bloco do try encerra
